_BASE_: DAQ_Online_R50.yaml
MODEL:
  META_ARCHITECTURE: "DVIS_DAQ_offline"
  VIDEO_HEAD:
    TRAINING_SELECT_THRESHOLD: 0.1
    INFERENCE_SELECT_THRESHOLD: 0.05
    AUX_INFERENCE_SELECT_THRESHOLD: 0.01
    OFFLINE_TOPK_NUM: 40

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (112000,)
  MAX_ITER: 160000

INPUT:
  SAMPLING_FRAME_NUM: 15
  SAMPLING_FRAME_RANGE: 7
  REVERSE_AGU: True

OUTPUT_DIR: './output_DAQ_Offline_R50_OVIS_160k'
