#!/usr/bin/env python3
"""
Visualize attention maps from JSON files.

This script loads attention maps from JSON files generated by the attention extraction
process and creates heatmap visualizations of the temporal attention matrices.
"""

import json
import argparse
import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from pathlib import Path
import logging

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)


def load_attention_data(json_file):
    """
    Load attention data from JSON file.
    
    Args:
        json_file (str): Path to the JSON file containing attention maps
        
    Returns:
        dict: Loaded attention data
    """
    with open(json_file, 'r') as f:
        data = json.load(f)
    
    logger.info(f"Loaded attention data for video {data['video_id']}")
    logger.info(f"Number of frames: {data['num_frames']}")
    logger.info(f"Number of attention maps: {data['num_maps']}")
    
    return data


def create_attention_heatmap(attention_weights, title="Attention Map", save_path=None, 
                           figsize=(12, 10), cmap='viridis', vmin=None, vmax=None):
    """
    Create a heatmap visualization of attention weights.
    
    Args:
        attention_weights (list or np.ndarray): 2D attention matrix
        title (str): Title for the plot
        save_path (str, optional): Path to save the plot
        figsize (tuple): Figure size (width, height)
        cmap (str): Colormap for the heatmap
        vmin (float, optional): Minimum value for color scaling
        vmax (float, optional): Maximum value for color scaling
    """
    # Convert to numpy array if it's a list
    if isinstance(attention_weights, list):
        attention_weights = np.array(attention_weights)
    
    # Ensure it's 2D
    if attention_weights.ndim != 2:
        raise ValueError(f"Expected 2D attention matrix, got {attention_weights.ndim}D")
    
    num_frames = attention_weights.shape[0]
    
    # Create the plot
    fig, ax = plt.subplots(figsize=figsize)
    
    # Create heatmap
    im = ax.imshow(attention_weights, cmap=cmap, aspect='auto', vmin=vmin, vmax=vmax)
    
    # Set labels and title
    ax.set_xlabel('Frame Index (Query)', fontsize=12)
    ax.set_ylabel('Frame Index (Key)', fontsize=12)
    ax.set_title(f'{title}\n({num_frames} × {num_frames} attention matrix)', fontsize=14)
    
    # Set tick labels
    ax.set_xticks(range(0, num_frames, max(1, num_frames // 10)))
    ax.set_yticks(range(0, num_frames, max(1, num_frames // 10)))
    
    # Add colorbar
    cbar = plt.colorbar(im, ax=ax)
    cbar.set_label('Attention Weight', fontsize=12)
    
    # Add grid for better readability
    ax.grid(True, alpha=0.3)
    
    # Adjust layout
    plt.tight_layout()
    
    # Save if path provided
    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        logger.info(f"Saved heatmap to: {save_path}")
    
    return fig, ax


def visualize_attention_maps(json_file, output_dir=None, show_plot=True, 
                           figsize=(12, 10), cmap='viridis'):
    """
    Visualize all attention maps from a JSON file.
    
    Args:
        json_file (str): Path to the JSON file
        output_dir (str, optional): Directory to save plots
        show_plot (bool): Whether to display the plot
        figsize (tuple): Figure size for plots
        cmap (str): Colormap for heatmaps
    """
    # Load data
    data = load_attention_data(json_file)
    
    # Set up output directory
    if output_dir is None:
        output_dir = os.path.dirname(json_file)
    else:
        os.makedirs(output_dir, exist_ok=True)
    
    # Get base filename for output
    base_name = Path(json_file).stem
    
    # Process each attention map
    for i, attn_map in enumerate(data['attention_maps']):
        layer_name = attn_map['layer']
        attention_weights = attn_map['attention_weights']
        
        logger.info(f"Processing attention map {i+1}/{len(data['attention_maps'])}: {layer_name}")
        logger.info(f"Attention matrix shape: {attn_map['shape']}")
        
        # Create title
        title = f"Temporal Attention Map - {layer_name}"
        
        # Add instance info if available
        if 'instance_info' in attn_map:
            inst_info = attn_map['instance_info']
            title += f"\nInstance ID: {inst_info.get('instance_id', 'N/A')}, "
            title += f"Rank: {inst_info.get('rank', 'N/A')}, "
            title += f"Confidence: {inst_info.get('confidence_score', 'N/A'):.4f}"
        
        # Create output filename
        output_filename = f"{base_name}_{layer_name.replace('refiner_time_self_attn_', 'layer_')}.png"
        output_path = os.path.join(output_dir, output_filename)
        
        # Create heatmap
        try:
            fig, ax = create_attention_heatmap(
                attention_weights, 
                title=title,
                save_path=output_path,
                figsize=figsize,
                cmap=cmap
            )
            
            if show_plot:
                plt.show()
            else:
                plt.close(fig)
                
        except Exception as e:
            logger.error(f"Error creating heatmap for {layer_name}: {e}")
            continue
    
    # Create summary plot if multiple attention maps
    if len(data['attention_maps']) > 1:
        create_summary_plot(data, output_dir, base_name, figsize, cmap)
    
    logger.info(f"Visualization complete. Plots saved to: {output_dir}")


def create_summary_plot(data, output_dir, base_name, figsize, cmap):
    """
    Create a summary plot showing all attention maps in subplots.
    
    Args:
        data (dict): Loaded attention data
        output_dir (str): Output directory
        base_name (str): Base filename
        figsize (tuple): Figure size
        cmap (str): Colormap
    """
    num_maps = len(data['attention_maps'])
    
    # Calculate subplot layout
    if num_maps == 1:
        return
    
    # Determine grid layout
    if num_maps <= 4:
        rows, cols = 2, 2
    elif num_maps <= 6:
        rows, cols = 2, 3
    elif num_maps <= 9:
        rows, cols = 3, 3
    else:
        rows, cols = 4, 4
    
    fig, axes = plt.subplots(rows, cols, figsize=(figsize[0] * cols / 2, figsize[1] * rows / 2))
    
    # Flatten axes for easier indexing
    if rows == 1:
        axes = [axes]
    elif cols == 1:
        axes = [[ax] for ax in axes]
    else:
        axes = axes.flatten()
    
    # Plot each attention map
    for i, attn_map in enumerate(data['attention_maps']):
        if i >= len(axes):
            break
            
        ax = axes[i]
        layer_name = attn_map['layer']
        attention_weights = np.array(attn_map['attention_weights'])
        
        # Create heatmap
        im = ax.imshow(attention_weights, cmap=cmap, aspect='auto')
        
        # Set title
        ax.set_title(f"{layer_name}", fontsize=10)
        ax.set_xlabel('Query Frame')
        ax.set_ylabel('Key Frame')
        
        # Add colorbar
        plt.colorbar(im, ax=ax, shrink=0.8)
    
    # Hide unused subplots
    for i in range(len(data['attention_maps']), len(axes)):
        axes[i].set_visible(False)
    
    # Set main title
    fig.suptitle(f"Attention Maps Summary - Video {data['video_id']}", fontsize=16)
    
    # Adjust layout
    plt.tight_layout()
    
    # Save summary plot
    summary_path = os.path.join(output_dir, f"{base_name}_summary.png")
    plt.savefig(summary_path, dpi=300, bbox_inches='tight')
    logger.info(f"Saved summary plot to: {summary_path}")
    
    plt.close(fig)


def main():
    """Main function to handle command line arguments and run visualization."""
    parser = argparse.ArgumentParser(description='Visualize attention maps from JSON files')
    parser.add_argument('json_file', help='Path to the JSON file containing attention maps')
    parser.add_argument('--output-dir', '-o', help='Output directory for plots (default: same as input file)')
    parser.add_argument('--no-show', action='store_true', help='Do not display plots (only save)')
    parser.add_argument('--figsize', nargs=2, type=float, default=[12, 10], 
                       help='Figure size as width height (default: 12 10)')
    parser.add_argument('--cmap', default='viridis', 
                       help='Colormap for heatmaps (default: viridis)')
    parser.add_argument('--verbose', '-v', action='store_true', help='Enable verbose logging')
    
    args = parser.parse_args()
    
    # Set logging level
    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)
    
    # Check if input file exists
    if not os.path.exists(args.json_file):
        logger.error(f"Input file not found: {args.json_file}")
        return 1
    
    # Run visualization
    try:
        visualize_attention_maps(
            json_file=args.json_file,
            output_dir=args.output_dir,
            show_plot=not args.no_show,
            figsize=tuple(args.figsize),
            cmap=args.cmap
        )
        return 0
    except Exception as e:
        logger.error(f"Error during visualization: {e}")
        return 1


if __name__ == "__main__":
    exit(main())
