_BASE_: DAQ_Online_VitAdapterL.yaml
MODEL:
  META_ARCHITECTURE: "DVIS_DAQ_offline"
  VIDEO_HEAD:
    TRAINING_SELECT_THRESHOLD: 0.02
    INFERENCE_SELECT_THRESHOLD: 0.01
    AUX_INFERENCE_SELECT_THRESHOLD: 0.01
    OFFLINE_TOPK_NUM: 40

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (112000,)
  MAX_ITER: 160000
  CHECKPOINT_PERIOD: 5000

INPUT:
  SAMPLING_FRAME_NUM: 15
  SAMPLING_FRAME_RANGE: 7
  REVERSE_AGU: True

OUTPUT_DIR: './output_DAQ_Offline_ViTL_YTVIS19_160k'