_BASE_: ../DVIS_Plus/DVIS_DAQ/configs/dvis_daq/ytvis21/vit_adapter/DAQ_Offline_VitAdapterL.yaml  # file to inherit settings from
MODEL:
  META_ARCHITECTURE: "DVIS_DAQ_offline"
  VIT_ADAPTER:
    FINETUNE: False
    NAME: 'vitl'
    VIT_WEIGHT: '/home/simone/checkpoints/dinov2_vitl14_pretrain.pth'
  VIDEO_HEAD:
    TRAINING_SELECT_THRESHOLD: 0.02
    INFERENCE_SELECT_THRESHOLD: 0.01
    AUX_INFERENCE_SELECT_THRESHOLD: 0.01
    OFFLINE_TOPK_NUM: 40
    USE_LOCAL_ATTN: True

SOLVER:
  IMS_PER_BATCH: 1
  STEPS: (112000,)
  MAX_ITER: 160000
  CHECKPOINT_PERIOD: 5000

INPUT:
  SAMPLING_FRAME_NUM: 15
  SAMPLING_FRAME_RANGE: 7
  REVERSE_AGU: True

DATASETS:
  DATASET_RATIO: [1.0] # Ratio for mixing multiple datasets (1.0 means use all of this dataset)
  DATASET_NEED_MAP: [False]  # whether the dataset needs category mapping (False = no mapping needed)... This is not needed for YTVisFishway
  DATASET_TYPE: ['video_instance']  # type of dataset (video_instance = video instance segmentation)
  TRAIN: ("ytvis_fishway_train",)  # training dataset
  TEST: ("ytvis_fishway_val",)  # testing dataset

OUTPUT_DIR: '/home/simone/fish-dvis/dvis-model-outputs'