_BASE_: ../../dvis_Plus/ytvis21/MinVIS_R50.yaml
MODEL:
  META_ARCHITECTURE: "DVIS_DAQ_online"
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "VideoMultiScaleMaskedTransformerDecoder_dvisPlus"
    REID_BRANCH: True
    TEST:
      MAX_NUM: 20
  VIDEO_HEAD:
    NUM_NEW_INS: 100
    NUM_SLOTS: 5
    TRAINING_SELECT_THRESHOLD: 0.02
    INFERENCE_SELECT_THRESHOLD: 0.01
    AUX_INFERENCE_SELECT_THRESHOLD: 0.01
    NOISE_FRAME_NUM: 5
    USING_THR: True

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (112000,)
  MAX_ITER: 160000
  CHECKPOINT_PERIOD: 5000

INPUT:
  SAMPLING_FRAME_NUM: 5
  SAMPLING_FRAME_RANGE: 2
  SAMPLING_FRAME_SHUFFLE: False
  USING_FRAME_NUM: [2, 5]
  STEPS: [10000]

TEST:
  EVAL_PERIOD: 0

OUTPUT_DIR: './output_DAQ_Online_R50_YTVIS21_160k'